#!groovy
//This is the increment pipeline which will normally be triggered manually (but can be done on every pull request)
//and will try to do the build and deploy for the service, which includes:
//Checkout GIT repo, compile, run code quality checks, run unit/integration/perf tests and build docker image

def pipelineScriptPath = "cicd/pipeline/"
def buildFlow = load pipelineScriptPath + "util/buildUtil.groovy"
def ENV_STAGE = 'dev'

pipeline {
    options {
        disableConcurrentBuilds()
    }
    agent {
        label 'java8-node-docker'
    }
    environment {
        DOCKER_HOST = 'tcp://dl1.aureacentral.com:2375'
    }

    stages {
        stage('Config env variables for development') {
            when {  branch 'develop' }
            steps {
                script {
                    ENV_STAGE='dev'
                }
            }
        }
        stage('Config env variables for master or staging') {
            when { anyOf { branch 'master'; branch 'staging';  } }
            steps {
                script {
                    ENV_STAGE='qa'
                }
            }
        }
        stage('Checkout code') {
            steps {
                script {
                    println("Deploying on env $ENV_STAGE with AUREA_API_UI_URL ${AUREA_API_UI_URL} and BACKEND_URL ${BACKEND_URL}")
                    buildFlow.checkout()
                }
            }
        }
        stage('Build UI') {
            steps {
                script {
                    buildFlow.buildUi()
                }
            }
        }
        stage('Build service') {
            steps {
                script {
                    // jacoco plugin not found in jervis yet
                    buildFlow.buildWithoutJacoco()
                }
            }
        }
        stage('Build and push service docker image') {
            when { anyOf { branch 'master'; branch 'staging'; branch 'develop' } }
            steps {
                script {
                    buildFlow.buildAndPushDocker(ENV_STAGE, pwd() + "/service/aurea-zero-based-api", "api")
                }
            }
        }
        stage('Push UI docker image') {
            when { anyOf { branch 'master'; branch 'staging'; branch 'develop' } }
            steps {
                script {
                    buildFlow.buildAndPushDocker(ENV_STAGE, pwd() + "/ui", "ui")
                }
            }
        }
        stage('Deployment') {
            when { anyOf { branch 'master'; branch 'staging'; branch 'develop' } }
            steps {
                script {
                    def deployFlow = load pipelineScriptPath + "util/deployUtil.groovy"
                    deployFlow.deploy()
                }
            }
        }
        stage('Preparing devspaces image') {
            when { anyOf { branch 'master'; branch 'staging'; branch 'develop' } }
            steps {
                script {
                    buildFlow.buildAndPushDocker("latest", pwd() + "/devspaces", "devspaces")
                }
            }
        }

    }
    post {
        always {
            script {
                def notifyFlow = load pipelineScriptPath + "util/notifyUtil.groovy"
                notifyFlow.notifyBuild(currentBuild.result)
                deleteDir()
            }
        }
    }
}
